EZ-26: added vertical_tabs_config module
srijanone/ezcontent pull request #181
Opened 2020-05-29 09:37 UTC by saurabh-2k17

2020-06-01 05:40 UTC, arshadkhan53 commented
Hi @saurabh-2k17 can we merge this into single commit (squash)?

2020-06-11 11:28 UTC, vaibhavjain-in requested changes
@saurabh-2k17 please do changes.

2020-06-11 11:28 UTC, vaibhavjain-in commented on config/install/content_lock.settings.yml
> +  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
Remove these 2 lines.

2020-06-11 11:28 UTC, vaibhavjain-in commented on config/install/system.action.block_content_break_lock_action.yml
> +uuid: 8e817ed2-2304-4caf-829f-a141f9c034dc
Remove this line.

2020-06-11 11:28 UTC, vaibhavjain-in commented on config/install/system.action.node_break_lock_action.yml
> +uuid: 2082bdea-027c-41da-840d-a8b767d372c3
Remove this line.

2020-06-11 11:28 UTC, vaibhavjain-in commented on config/install/user.role.editor.yml
> +uuid: c23ccd9c-e9f5-4f75-bea1-029eff8e81be
Remove this file. This file already exists here - https://github.com/srijanone/ezcontent/blob/8.x/modules/ezcontent_user/config/install/user.role.editor.yml
Is there a change that needs to be pushed ?

2020-06-11 11:28 UTC, vaibhavjain-in commented on ezcontent.info.yml
> +  - content_lock
Please remove this line as its submodule will enable parent module `content_lock`

2020-06-11 12:14 UTC, vaibhavjain-in approved these changes
LGTM

2020-06-11 12:15 UTC, merged