EZ-599: Rename Cards View Mode as 1xn and 3xn cards
srijanone/ezcontent pull request #286
Opened 2020-09-28 06:17 UTC by saurabh-2k17

2020-09-28 06:30 UTC, arshadkhan53 commented on ezcontent.libraries.yml
> +    - core/drupal
why we need other dependencies here, i believe only required dependency is `core/jquery`

2020-09-28 06:30 UTC, arshadkhan53 commented on ezcontent.profile
> +function ezcontent_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
The library should only be attached to cards block, also i believe it would be better to move these code to block level, inside cards block module.

2020-09-28 06:30 UTC, arshadkhan53 commented on js/ezcontent.js
> +    Drupal.behaviors.dlp_faq = {
behaviour name should be feature specific.

2020-09-28 06:30 UTC, arshadkhan53 commented on ezcontent.libraries.yml
> +ezcontentjs:
We can move these file on block, level and change the library and js file name specific to that block and feature.

2020-09-28 11:38 UTC, arshadkhan53 requested changes

2020-09-28 11:38 UTC, arshadkhan53 commented on modules/ezcontent_block/modules/ezcontent_block_cards/ezcontent_block_cards.module
> +function ezcontent_block_type_form_alter(array &$form, FormStateInterface &$form_state, string $block_type) {
wrong hook name, please check.

2020-12-03 06:52 UTC, Vinay15 commented on modules/ezcontent_block/modules/ezcontent_block_cards/ezcontent_block_cards.module
> +    $pluginId = $blockComponent->getPluginId();
should we avoid the assignment of variable here?
`if ($blockComponent->getPluginId() === 'inline_block:cards') {`

Rest, LGTM

2020-12-03 06:52 UTC, Vinay15 approved these changes

2020-12-03 07:29 UTC, arshadkhan53 approved these changes
LGTM

2020-12-03 07:29 UTC, merged