Enabled login with email only.
srijanone/ezcontent pull request #66
Opened 2020-01-28 10:16 UTC by arshadkhan53

Enabled login with email only.

2020-01-29 10:34 UTC, vaibhavjain-in requested changes
@arshadkhan53 Please see some minor issues. Please cater to the feedback.

2020-01-29 10:34 UTC, vaibhavjain-in commented on modules/ezcontent_user/ezcontent_user.info.yml
> +name: EZContent USER
Can the name be `EZContent User Feature`

2020-01-29 10:34 UTC, vaibhavjain-in commented on modules/ezcontent_user/ezcontent_user.info.yml
> +description: 'Alter user forms and manage user entity.'
Let the description be `Provides user based features.`

2020-01-29 10:34 UTC, vaibhavjain-in commented on modules/ezcontent_user/ezcontent_user.info.yml
> +package: EZContent USER
Let the package name be `EZContent User`

2020-01-29 10:46 UTC, vaibhavjain-in approved these changes
Looks good.

2020-01-29 10:46 UTC, merged

2020-10-28 01:22 UTC, ddfiberglass commented on composer.json
> +    "drupal/login_onlyemail": "^1.5",
I have used docker images for EzContent installation. What is the default email and password for log in?

The installation steps is exact as (https://hub.docker.com/r/srijanlabs/ezcontent) below:

Create a network
docker network create ez-nw

Create containers
docker run --rm --name mysql -e MYSQL_ROOT_PASSWORD=drupal -e MYSQL_USER=drupal -e MYSQL_PASSWORD=drupal -e MYSQL_DATABASE=drupal --network ez-nw -p 3306:3306 -d mysql:5.7
docker run --rm --name ezcontent_drupal --network ez-nw -e DB_HOST=mysql -e DB_USER=drupal -e DB_PASSWORD=drupal -e DB_PORT=3306 -e DB_NAME=drupal -p 8062:8080 -d srijanlabs/ezcontent:8.x
Run following command to install the Ezcontent Stack
docker exec -it ezcontent_drupal sh -c "php -d memory_limit=-1 ./vendor/bin/drush si ezcontent --db-url='mysql://drupal:drupal@mysql/drupal' --site-name='EZ Content' --account-name='srijan' --account-pass='admin12345' -y && php -d memory_limit=-1 ./vendor/bin/drush en ezcontent_demo -y && php -d memory_limit=-1 ./vendor/bin/drush en ezcontent_api -y && php -d memory_limit=-1 ./vendor/bin/drush en ezcontent_api -y"