Preview module
srijanone/ezcontent pull request #7
Opened 2019-10-21 09:13 UTC by kuldev

2019-10-21 09:43 UTC, vaibhavjain-in requested changes

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/css/global-css.css
> +}
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.info.yml
> +  - access_unpublished
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.info.yml
> +dependencies:
Please add the module `access_unpublished` in composer.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.libraries.yml
> +    js/global-js.js: {}
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.links.menu.yml
> +  parent: system.admin_config_system
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.module
> +    }
Please get the formatting correct.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/ezcontent_preview.routing.yml
> +    node: \d+
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/js/global-js.js
> +})(jQuery, Drupal);
Please leave a new line at EOF.

2019-10-21 09:43 UTC, vaibhavjain-in commented on modules/ezcontent_preview/src/Form/PreviewConfigForm.php
> +
Please remove additional lines.

2019-10-23 06:11 UTC, kuldev commented on modules/ezcontent_preview/css/global-css.css
> +}
it should be there.

2019-10-23 06:32 UTC, vaibhavjain-in approved these changes

2019-10-23 06:32 UTC, merged